name: Release Artifacts
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git/checkouts
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          fail-on-cache-miss: true
      - name: Build Artifacts
        run: |
          docker run \
            -v "$GITHUB_WORKSPACE":/code \
            -v ~/.cargo/registry:/usr/local/cargo/registry \
            -v ~/.cargo/git:/usr/local/cargo/git \
            cosmwasm/workspace-optimizer:0.15.0
          tar -zcvf cosmwasm-artifacts.tar.gz artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: cosmwasm-artifacts.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
